version: '3'
services:
  testlive-ui:
    image: testlive-ui
    ports:
      - "8080:8080"
    build:
      context: ./testlive-ui
    command: bash -c "npm run serve"
    volumes:
      - ./testlive-ui:/app
    networks:
      - custom

  testlive-web:
    image: testlive-web
    ports:
      - "8000:8000"
      - "9000:9000"
    volumes:
      - ./testlive-web:/opt/app
    command: bash -c "python -m debugpy --listen 0.0.0.0:9000 start.py"
    env_file:
      - .env
    build:
      context: ./testlive-web
    depends_on:
      postgres:
        condition: service_started
    networks:
      - custom
    
  nginx:
    image: nginx
    ports:
      - "80:80"
    build:
      context: ./nginx
    depends_on:
      - testlive-web
      - testlive-ui
    networks:
      - custom

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=tester
      - POSTGRES_PASSWORD=testliver
      - POSTGRES_DB=testlivedb
    ports:
      - "5432:5432"
    restart: always
    networks:
      - custom

networks:
    custom:
      driver: bridge